
version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yaml --kms-key-id 1d339f25-c388-4127-9c93-d36ce1e92a96 --s3-bucket jwatkins-codedeploy-test --output-template-file outputSamTemplate.yaml --debug
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml


